"""baseline banco ARA

Revision ID: b553a628dade
Revises: 
Create Date: 2026-09-30 17:07:06.587603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b553a628dade'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conversa',
    sa.Column('id_conversa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', sa.Enum('ATIVA', 'ARQUIVADA', 'ENCERRADA', name='status_conversa'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_conversa')
    )
    op.create_table('memoria',
    sa.Column('id_memoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_memoria', sa.String(length=50), nullable=False),
    sa.Column('conteudo', mysql.LONGTEXT(), nullable=False),
    sa.Column('importancia', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_expiracao', sa.DateTime(), nullable=True),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_memoria')
    )
    op.create_table('perfil_personalizacao',
    sa.Column('id_perfil', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tom', sa.String(length=30), server_default='ADAPTATIVO', nullable=False),
    sa.Column('formalidade', sa.String(length=30), server_default='ADAPTATIVA', nullable=False),
    sa.Column('nivel_detalhe', sa.String(length=20), server_default='MEDIO', nullable=False),
    sa.Column('usar_emojis', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('estilo_resposta', sa.String(length=30), server_default='NATURAL', nullable=False),
    sa.Column('instrucoes_personais', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_perfil')
    )
    op.create_index(op.f('ix_perfil_personalizacao_id_usuario'), 'perfil_personalizacao', ['id_usuario'], unique=True)
    op.create_table('tarefa',
    sa.Column('id_tarefa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('prioridade', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', name='statustarefa'), server_default=sa.text("'PENDENTE'"), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('data_limite', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_tarefa')
    )
    op.create_table('contexto_agente',
    sa.Column('id_contexto', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_conversa', sa.Integer(), nullable=False),
    sa.Column('ultima_tarefa_id', sa.Integer(), nullable=True),
    sa.Column('ultimo_lembrete_id', sa.Integer(), nullable=True),
    sa.Column('ultima_ferramenta', sa.String(length=100), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_conversa'], ['conversa.id_conversa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ultima_tarefa_id'], ['tarefa.id_tarefa'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_contexto'),
    sa.UniqueConstraint('id_conversa')
    )
    op.create_table('entidade_contextual',
    sa.Column('id_entidade_contextual', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_conversa', sa.Integer(), nullable=False),
    sa.Column('tipo_entidade', sa.String(length=50), nullable=False),
    sa.Column('id_entidade', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('ordem_contexto', sa.Integer(), nullable=False),
    sa.Column('data_mencao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_conversa'], ['conversa.id_conversa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_entidade_contextual')
    )
    op.create_table('lembrete',
    sa.Column('id_lembrete', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_tarefa', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('recorrencia', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', name='statuslembrete'), server_default=sa.text("'PENDENTE'"), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_tarefa'], ['tarefa.id_tarefa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_lembrete')
    )
    op.create_table('mensagem',
    sa.Column('id_mensagem', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_conversa', sa.Integer(), nullable=False),
    sa.Column('remetente', sa.Enum('USUARIO', 'ARA', 'SISTEMA', name='remetente_mensagem'), nullable=False),
    sa.Column('conteudo', mysql.LONGTEXT(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('data_envio', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('modelo_ia', sa.String(length=100), nullable=True),
    sa.Column('tokens_entrada', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tokens_saida', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tempo_processamento', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['id_conversa'], ['conversa.id_conversa'], ),
    sa.PrimaryKeyConstraint('id_mensagem')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagem')
    op.drop_table('lembrete')
    op.drop_table('entidade_contextual')
    op.drop_table('contexto_agente')
    op.drop_table('tarefa')
    op.drop_index(op.f('ix_perfil_personalizacao_id_usuario'), table_name='perfil_personalizacao')
    op.drop_table('perfil_personalizacao')
    op.drop_table('memoria')
    op.drop_table('conversa')
    op.drop_table('usuario')
    # ### end Alembic commands ###
